version: '3'

services:
  backend:
    build:
      context: ./api
    command: gunicorn api.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  front-end:
    build:
      context: ./frontend
    volumes:
      - build_folder:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend

volumes:
   build_folder:
